# Generated by Django 4.2.4 on 2023-10-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=60)),
                ('dni', models.CharField(max_length=8)),
                ('email', models.EmailField(default='to1@example.com', max_length=100)),
                ('direccion', models.CharField(default='Domicilio..', max_length=100)),
            ],
        ),
    ]
