# Generated by Django 4.2.5 on 2023-10-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_persona_direccion_alter_persona_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(default='to1@example.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(default='Domicilio..', max_length=100),
        ),
    ]
