# Generated by Django 4.2.5 on 2023-11-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_grupofamiliar_remove_pago_socio_sociogrupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioMensualidadFija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='grupofamiliar',
            options={'verbose_name_plural': 'grupos familiares'},
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='socios.categoria')),
            ],
        ),
    ]
