# Generated by Django 4.2.5 on 2023-11-27 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_cambiomensualidadfija_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='cuerpo',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='comunicado',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 11, 27)),
        ),
    ]
