# Generated by Django 4.2.5 on 2023-11-27 18:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_comunicado_cuerpo_comunicado_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='docente_de_curso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 18, 2, 19, 878360, tzinfo=datetime.timezone.utc)),
        ),
    ]
